on:
  workflow_call:
    outputs:
      changelog:
        description: 'short github sha'
        value: ${{ jobs.main.outputs.changelog }}
      commitish:
        description: 'short github sha'
        value: ${{ jobs.main.outputs.commitish }}
      environment:
        description: 'version'
        value: ${{ jobs.main.outputs.environment }}
      node-version:
        description: 'node.js version'
        value: ${{ jobs.main.outputs.node-version }}
      pnpm-version:
        description: 'pnpm version'
        value: ${{ jobs.main.outputs.pnpm-version }}
      prerelease:
        description: 'is prerelease'
        value: ${{ jobs.main.outputs.prerelease }}
      ref:
        description: 'ref'
        value: ${{ jobs.main.outputs.ref }}
      version:
        description: 'version'
        value: ${{ jobs.main.outputs.version }}
jobs:
  main:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.action-context.outputs.changelog }}
      commitish: ${{ steps.action-context.outputs.commitish }}
      environment: ${{ steps.action-context.outputs.environment }}
      node-version: ${{ steps.node-version.outputs.value }}
      pnpm-version: ${{ steps.pnpm-version.outputs.value }}
      prerelease: ${{ fromJSON(steps.action-context.outputs.prerelease) }}
      ref: ${{ steps.ref.outputs.value }}
      version: ${{ steps.action-context.outputs.version }}
    steps:
      - id: ref
        name: ref
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "value=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          else
            echo "value=${GITHUB_REF}" >> $GITHUB_OUTPUT
          fi
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.ref.outputs.value }}
          fetch-depth: 0
      - id: action-context
        uses: escapace/action-context@v0.6.1
        with:
          token: ${{ github.token }}
      - id: node-version
        name: node-version
        shell: bash
        run: |
          echo "value=$(cat package.json | jq -r .engines.node | grep -oP '([0-9]+)\.([0-9]+)\.([0-9]+)' | head -n 1)"  >> $GITHUB_OUTPUT
      - id: pnpm-version
        name: pnpm-version
        shell: bash
        run: |
          echo "value=$(cat package.json | jq -r .engines.pnpm | grep -oP '([0-9]+)\.([0-9]+)\.([0-9]+)' | head -n 1)" >> $GITHUB_OUTPUT
